# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='type',
        ),
        migrations.AlterField(
            model_name='doc',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
