# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usager',
            name='user_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
