# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20161230_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_titre', models.CharField(max_length=500)),
                ('fichier_description', models.CharField(max_length=1000)),
                ('fichier_file', models.FileField(upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Personne')),
            ],
        ),
    ]
