# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
